### ISSUE TITLE
Ajout d'un lien vers le shop sur "donateur" ou "payant"

### ISSUE THREAD

**Issue by DaikiKaminari** [Mineaurion/Website_new#1]
Dans le statut du serveur ([ici](https://mineaurion.github.io/Website_new/statut.html)) les joueurs peuvent voir que certains serveurs sont payant ou réservés aux donateurs, il faudrait que ces textes soient des liens vers le shop pour qu'ils puissent facilement se rendre compte des prix. L'idée est de facilité l'accès, ce qui est important pour un service payant, les gens sont souvent rebuté par une simple flemme.

**Comment by vaillki** [comment]
Salut à toi,
Je viens de l'ajouter ! Je le poste ce soir, j'attends ton retour.
