### ISSUE TITLE
responsive problème

### ISSUE THREAD

**Issue by Gaetann18** [Mineaurion/Website_new#5]
sous firefox & chrome le responsive est "étrange" et le site déborde du cadre 
![image](https://user-images.githubusercontent.com/43312235/205990954-e4fd5280-49d9-44b5-acec-020f72c398fc.png)
![image](https://user-images.githubusercontent.com/43312235/205991062-4256ab58-ab66-45e5-9743-e46494e31bbf.png)

alors sur sous edge : 
![image](https://user-images.githubusercontent.com/43312235/205991367-211a3c39-b4df-4823-8269-e54e0575d7d6.png)

**Comment by Gaetann18** [comment]
sur un écran ultra wide les boutons ne s'adaptent pas : 
![image](https://user-images.githubusercontent.com/43312235/205993461-78841185-7658-4d15-8be7-1861dc5ee774.png)

**Comment by vaillki** [comment]
Je dois voir pourquoi cela me fait ça car sur linux cela fonctionne nickel 😞
